# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: "mac"
env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":swift: SwiftFormat Linting"
    key: swiftformat-lint
    plugins:
      - docker#v5.12.0:
          image: "ghcr.io/nicklockwood/swiftformat:$SWIFTFORMAT_VERSION"
          command: [ "GravatarApp", "GravatarAppTests", "Packages", "--lint" ]
          workdir: "${BUILDKITE_BUILD_CHECKOUT_PATH}"
    notify:
      - github_commit_status:
          context: "SwiftFormat Linting"
    agents:
      queue: "default"

  - label: "🧪 Tests"
    key: tests
    command: |
      make test
    notify:
      - github_commit_status:
          context: "Unit tests"
