#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export IMAGE_ID="xcode-16.4"
export CI_TOOLKIT="automattic/a8c-ci-toolkit#5.3.1"
SWIFTFORMAT_VERSION="$( awk '/^--minversion/ { print $2 }' .swiftformat )"
export SWIFTFORMAT_VERSION
