# frozen_string_literal: true

require 'dotenv'
require 'json'
require 'xcodeproj'

fastlane_version '2.0'

PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))

CODE_SIGNING_STORAGE_OPTIONS = {
  storage_mode: 's3',
  s3_bucket: 'a8c-fastlane-match',
  s3_region: 'us-east-2'
}.freeze

# Required for sync_code_signing to authenticate with S3.
CODE_SIGNING_ENV_VARS = %w[
  MATCH_S3_ACCESS_KEY
  MATCH_S3_SECRET_ACCESS_KEY
  MATCH_PASSWORD
].freeze

PROJECT_XCCONFIG = Xcodeproj::Config.new(File.join(PROJECT_ROOT_FOLDER, 'Config', 'Project.xcconfig'))
APP_STORE_XCCONFIG = Xcodeproj::Config.new(File.join(PROJECT_ROOT_FOLDER, 'Config', 'GravatarApp.common.xcconfig'))
ENTERPRISE_XCCONFIG = Xcodeproj::Config.new(File.join(PROJECT_ROOT_FOLDER, 'Config', 'GravatarApp.enterprise.xcconfig'))

# Required for app_store_connect_api_key to generate the key information to pass down the call chain.
ASC_API_KEY_ENV_VARS = %w[
  APP_STORE_CONNECT_API_KEY_KEY_ID
  APP_STORE_CONNECT_API_KEY_ISSUER_ID
  APP_STORE_CONNECT_API_KEY_KEY
].freeze

require_relative 'lib/env_manager'
require_relative 'lib/code_signing_helpers'

before_all do
  # This is necessary for 'match' to work correctly in CI. When running
  # locally, it has no effect so it's safe to run it before all lanes.
  setup_ci if runner.current_platform == :ios

  EnvManager.set_up(env_file_name: 'gravatar-ios.env')
end

default_platform :ios

platform :ios do
  # Download and configure code signing certificates and provisioning profiles for the App Store build.
  #
  # @param readonly [Boolean] If false, will generate new provisioning profiles if the ones available are missing or invalid.
  #
  desc 'Download and configure code signing certificates and provisioning profiles for the App Store build.'
  lane :configure_code_signing_app_store do |readonly: true|
    configure_code_signing(app_identifier: app_bundle_identifier_app_store!, type: 'appstore', team_id: asc_team_id!, readonly: readonly)
  end

  # Download and configure code signing certificates and provisioning profiles for the Enterprise build (Prototype Build).
  #
  # @param readonly [Boolean] If false, will generate new provisioning profiles if the ones available are missing or invalid.
  #
  desc 'Download and configure code signing certificates and provisioning profiles for the Enterprise build (Prototype Build).'
  lane :configure_code_signing_enterprise do |readonly: true|
    configure_code_signing(app_identifier: app_bundle_identifier_enterprise!, type: 'enterprise', team_id: enterprise_team_id!, readonly: readonly)
  end
end

def configure_code_signing(app_identifier:, type:, team_id:, readonly:)
  EnvManager.require_env_vars!(*CODE_SIGNING_ENV_VARS)

  unless readonly
    case type
    when 'appstore'
      # When readonly = false and type = appstore, we need the API key instantiated to connect with App Store Connect.
      EnvManager.require_env_vars!(*ASC_API_KEY_ENV_VARS)
      api_key = app_store_connect_api_key
    when 'enterprise'
      # The Enterprise account APIs do not support authentication via API key.
      # If we want to modify data (readonly = false) we need to authenticate manually.
      prompt_user_for_app_store_connect_credentials
    else
      UI.user_error!("Unsupported code signing type: '#{type}'")
    end
  end

  sync_code_signing(
    type: type,
    team_id: team_id,
    api_key: api_key,
    app_identifier: app_identifier,
    readonly: readonly,
    **CODE_SIGNING_STORAGE_OPTIONS
  )
end

def asc_team_id!
  read_from_xcconfig!(key: 'DEVELOPMENT_TEAM', xcconfig: PROJECT_XCCONFIG)
end

def enterprise_team_id!
  read_from_xcconfig!(key: 'DEVELOPMENT_TEAM', xcconfig: ENTERPRISE_XCCONFIG)
end

def app_bundle_identifier_app_store!
  read_from_xcconfig!(key: 'PRODUCT_BUNDLE_IDENTIFIER')
end

def app_bundle_identifier_enterprise!
  read_from_xcconfig!(key: 'PRODUCT_BUNDLE_IDENTIFIER', xcconfig: ENTERPRISE_XCCONFIG)
end

def read_from_xcconfig!(key:, xcconfig: APP_STORE_XCCONFIG)
  configs = xcconfig.attributes

  UI.user_error!("Could not find value for #{key} in xcconfig!") unless configs.key?(key)

  configs[key]
end
