# frozen_string_literal: true

require 'dotenv'
require 'json'
require 'xcodeproj'

fastlane_version '2.0'

PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))

CODE_SIGNING_STORAGE_OPTIONS = {
  storage_mode: 's3',
  s3_bucket: 'a8c-fastlane-match',
  s3_region: 'us-east-2'
}.freeze

# Required for sync_code_signing to authenticate with S3.
CODE_SIGNING_ENV_VARS = %w[
  MATCH_S3_ACCESS_KEY
  MATCH_S3_SECRET_ACCESS_KEY
  MATCH_PASSWORD
].freeze

PROJECT_XCCONFIG = Xcodeproj::Config.new(File.join(PROJECT_ROOT_FOLDER, 'Config', 'Project.xcconfig'))
APP_STORE_XCCONFIG = Xcodeproj::Config.new(File.join(PROJECT_ROOT_FOLDER, 'Config', 'GravatarApp.common.xcconfig'))
ENTERPRISE_XCCONFIG_PATH = File.join(PROJECT_ROOT_FOLDER, 'Config', 'GravatarApp.enterprise.xcconfig')
ENTERPRISE_XCCONFIG = Xcodeproj::Config.new(ENTERPRISE_XCCONFIG_PATH)

ARTIFACTS_FOLDER = File.join(PROJECT_ROOT_FOLDER, '.build', 'artifacts')

PROTOTYPE_BUILD_NAME = 'GravatarApp-Prototype'

FIREBASE_APP_ID = '1:124902176124:ios:7bffd4c3c7143e3a1620f9'
FIREBASE_TESTERS_GROUP = 'gravatar-ios---prototype-builds'

GITHUB_REPO = 'Automattic/Gravatar-iOS'

# Required for app_store_connect_api_key to generate the key information to pass down the call chain.
ASC_API_KEY_ENV_VARS = %w[
  APP_STORE_CONNECT_API_KEY_KEY_ID
  APP_STORE_CONNECT_API_KEY_ISSUER_ID
  APP_STORE_CONNECT_API_KEY_KEY
].freeze

GLOTPRESS_PROJECT_URL = 'https://translate.wordpress.com/projects/gravatar/gravatar-ios'
LOCALIZATIONS_ROOT = File.join('GravatarApp', 'Resources')

# List of locales used for the app strings (GlotPress code => `*.lproj` folder name)
GLOTPRESS_TO_LPROJ_APP_LOCALE_CODES = {
  'ar' => 'ar',         # Arabic
  'de' => 'de',         # German
  'es' => 'es',         # Spanish
  'fr' => 'fr',         # French
  'he' => 'he',         # Hebrew
  'id' => 'id',         # Indonesian
  'it' => 'it',         # Italian
  'ja' => 'ja',         # Japanese
  'ko' => 'ko',         # Korean
  'nl' => 'nl',         # Dutch
  'pt-br' => 'pt-BR',   # Portuguese (Brazil)
  'ru' => 'ru',         # Russian
  'sv' => 'sv',         # Swedish
  'tr' => 'tr',         # Turkish
  'zh-cn' => 'zh-Hans', # Chinese (China)
  'zh-tw' => 'zh-Hant'  # Chinese (Taiwan)
}.freeze

require_relative 'lib/env_manager'
require_relative 'lib/code_signing_helpers'

before_all do
  # This is necessary for 'match' to work correctly in CI. When running
  # locally, it has no effect so it's safe to run it before all lanes.
  setup_ci if runner.current_platform == :ios

  EnvManager.set_up(env_file_name: 'gravatar-ios.env')
end

default_platform :ios

platform :ios do
  # Builds the app binary for Enterprise distribution (Prototype Build)
  #
  # @param fetch_code_signing [Boolean] If true, will call `configure_code_signing_enterprise` before building. Recommended on CI.
  # @param build_number [String] The build number to use for the build. When in CI, defaults to the value of `BUILDKITE_BUILD_NUMBER` environment variable.
  # @param version [String] The version to use for the build. When in CI, defaults to the PR number, falling back to the branch name.
  #
  lane :build_prototype do |fetch_code_signing: true, build_number: build_number_from_ci, version: pr_number_or_branch_name_from_ci|
    if fetch_code_signing
      configure_code_signing_enterprise
    else
      UI.message('Skipping fetching certificates and provisioning profiles as requested.')
    end

    build_app(
      scheme: 'GravatarApp',
      configuration: 'Enterprise',
      # Explicitly set iOS destination to avoid xcodebuild accidentally picking up tvOS
      destination: 'generic/platform=iOS',
      include_bitcode: false,
      include_symbols: true,
      clean: true,
      xcargs: { MARKETING_VERSION: version, CURRENT_PROJECT_VERSION: build_number },
      output_directory: ARTIFACTS_FOLDER,
      output_name: PROTOTYPE_BUILD_NAME,
      export_options: {
        method: 'enterprise',
        manageAppVersionAndBuildNumber: false
      }
    )
  end

  # Distributes the Prototype Build to Firebase App Distribution
  #
  lane :distribute_prototype do |ipa_path: File.join(ARTIFACTS_FOLDER, "#{PROTOTYPE_BUILD_NAME}.ipa")|
    EnvManager.require_env_vars!('FIREBASE_APP_DISTRIBUTION_ACCOUNT_KEY')

    release_notes = <<~NOTES
      Pull Request: ##{pull_request_number || 'N/A'}
      Branch: `#{branch_name_from_ci || 'N/A'}`
      Commit: `#{commit_hash_from_ci || 'N/A'}[0...7]`
    NOTES

    firebase_app_distribution(
      app: FIREBASE_APP_ID,
      ipa_path: ipa_path,
      service_credentials_json_data: EnvManager.get_required_env!('FIREBASE_APP_DISTRIBUTION_ACCOUNT_KEY'),
      release_notes: release_notes,
      groups: FIREBASE_TESTERS_GROUP
    )

    next if pull_request_number.nil?

    comment_on_pr(
      project: GITHUB_REPO,
      pr_number: pull_request_number,
      reuse_identifier: 'prototype-build-link',
      body: prototype_build_details_comment(
        app_display_name: 'Gravatar Prototype Build',
        fold: true
      )
    )
  end

  # Download and configure code signing certificates and provisioning profiles for the App Store build.
  #
  # @param readonly [Boolean] If false, will generate new provisioning profiles if the ones available are missing or invalid.
  #
  desc 'Download and configure code signing certificates and provisioning profiles for the App Store build.'
  lane :configure_code_signing_app_store do |readonly: true|
    configure_code_signing(app_identifier: app_bundle_identifier_app_store!, type: 'appstore', team_id: asc_team_id!, readonly: readonly)
  end

  # Download and configure code signing certificates and provisioning profiles for the Enterprise build (Prototype Build).
  #
  # @param readonly [Boolean] If false, will generate new provisioning profiles if the ones available are missing or invalid.
  #
  desc 'Download and configure code signing certificates and provisioning profiles for the Enterprise build (Prototype Build).'
  lane :configure_code_signing_enterprise do |readonly: true|
    configure_code_signing(app_identifier: app_bundle_identifier_enterprise!, type: 'enterprise', team_id: enterprise_team_id!, readonly: readonly)
  end

  # Generates the `.strings` files for the base language based on the app's source code.
  #
  lane :generate_strings do |skip_commit: false|
    gravatar_app_path = File.join(PROJECT_ROOT_FOLDER, 'GravatarApp')
    en_lproj_path = File.join(gravatar_app_path, 'Resources', 'en.lproj')

    # Use release-toolkit which uses `genstrings` to generate strings
    ios_generate_strings_file_from_code(
      paths: [gravatar_app_path],
      output_dir: en_lproj_path,
      output_encoding: 'UTF-8',
      routines: ['NSLocalizedString'],
      quiet: false
    )

    next if skip_commit

    git_add(path: en_lproj_path)
    git_commit(
      path: en_lproj_path,
      message: 'Update strings in base locale',
      allow_nothing_to_commit: true
    )
  end

  # Download the latest localizations from GlotPress and update the app accordingly.
  #
  # @param skip_commit [Boolean] Whether to skip committing the changes to git (default: false)
  #
  lane :download_translations do |skip_commit: false|
    check_translation_progress(
      glotpress_url: GLOTPRESS_PROJECT_URL,
      abort_on_violations: false,
      skip_confirm: true
    )

    ios_download_strings_files_from_glotpress(
      project_url: GLOTPRESS_PROJECT_URL,
      locales: GLOTPRESS_TO_LPROJ_APP_LOCALE_CODES,
      download_dir: LOCALIZATIONS_ROOT
    )

    ios_lint_localizations(
      input_dir: LOCALIZATIONS_ROOT
    )

    next if skip_commit

    git_add(path: LOCALIZATIONS_ROOT)
    git_commit(
      path: LOCALIZATIONS_ROOT,
      message: 'Update localizations',
      allow_nothing_to_commit: true
    )
  end
end

def configure_code_signing(app_identifier:, type:, team_id:, readonly:)
  EnvManager.require_env_vars!(*CODE_SIGNING_ENV_VARS)

  unless readonly
    case type
    when 'appstore'
      # When readonly = false and type = appstore, we need the API key instantiated to connect with App Store Connect.
      EnvManager.require_env_vars!(*ASC_API_KEY_ENV_VARS)
      api_key = app_store_connect_api_key
    when 'enterprise'
      # The Enterprise account APIs do not support authentication via API key.
      # If we want to modify data (readonly = false) we need to authenticate manually.
      prompt_user_for_app_store_connect_credentials
    else
      UI.user_error!("Unsupported code signing type: '#{type}'")
    end
  end

  sync_code_signing(
    type: type,
    team_id: team_id,
    api_key: api_key,
    app_identifier: app_identifier,
    readonly: readonly,
    **CODE_SIGNING_STORAGE_OPTIONS
  )
end

def asc_team_id!
  read_from_xcconfig!(key: 'DEVELOPMENT_TEAM', xcconfig: PROJECT_XCCONFIG)
end

def enterprise_team_id!
  read_from_xcconfig!(key: 'DEVELOPMENT_TEAM', xcconfig: ENTERPRISE_XCCONFIG)
end

def app_bundle_identifier_app_store!
  read_from_xcconfig!(key: 'PRODUCT_BUNDLE_IDENTIFIER')
end

def app_bundle_identifier_enterprise!
  read_from_xcconfig!(key: 'PRODUCT_BUNDLE_IDENTIFIER', xcconfig: ENTERPRISE_XCCONFIG)
end

def read_from_xcconfig!(key:, xcconfig: APP_STORE_XCCONFIG)
  configs = xcconfig.attributes

  UI.user_error!("Could not find value for #{key} in xcconfig!") unless configs.key?(key)

  configs[key]
end

def build_number_from_ci
  ENV.fetch('BUILDKITE_BUILD_NUMBER', '0')
end

def pr_number_or_branch_name_from_ci
  pull_request_number&.then { |num| "PR ##{num}" } || branch_name_from_ci || git_branch
end

def branch_name_from_ci
  ENV.fetch('BUILDKITE_BRANCH', nil)
end

def commit_hash_from_ci
  ENV.fetch('BUILDKITE_COMMIT', nil)
end

def pull_request_number
  # Buildkite sets this env var to the PR number if on a PR, but to 'false' (and not nil) if not on a PR
  pr_num = ENV.fetch('BUILDKITE_PULL_REQUEST', 'false')
  pr_num == 'false' ? nil : Integer(pr_num)
end
